server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
        namespaces:
          - booking
          - festival
          - payment
          - user
        service-labels:
          expose-via-spring-gateway: "true"
    gateway:
      default-filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/' + serviceId + '/**'"
          filters:
            - name: StripPrefix
              args:
                parts: 1

jwt:
  private-pem-path: classpath:keys/private.pem
  public-pem-path: classpath:keys/public.pem



management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.discovery: DEBUG
    org.springframework.cloud.kubernetes.discovery: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG