server:
  port: 10000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: http://localhost:8080
              predicates:
                - Path=/api/user/**,/api/addresses/**,/api/admin/**,/api/users/**,/api/mail/**,/api/auth/**,/api/myPage/**
            - id: user-swagger
              uri: http://localhost:8080
              predicates:
                - Path=/api/user/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1

            - id: payment
              uri: http://localhost:8081
              predicates:
                - Path=/api/payments/**,/api/tekcitpay/**
            - id: payment-swagger
              uri: http://localhost:8081
              predicates:
                - Path=/api/payments/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1

            - id: booking
              uri: http://localhost:8082
              predicates:
                - Path=/api/booking/**,/api/qr/**,/api/host/**,/api/capcha/**,/api/transfer/**,/api/ticket/**,/api/statistics/**,/ws/**

            - id: booking-swagger
              uri: http://localhost:8082
              predicates:
                - Path=/api/booking/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1

            - id: festival
              uri: http://localhost:8083
              predicates:
                - Path=/api/festival/**
            - id: festival-swagger
              uri: http://localhost:8083
              predicates:
                - Path=/api/festival/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1
jwt:
  private-pem-path: classpath:keys/private.pem
  public-pem-path: classpath:keys/public.pem


# cors url 설정
cors:
  url:
    - http://localhost:5173
    - http://127.0.0.1:5173
    - http://localhost:5174
    - http://127.0.0.1:5174


management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.discovery: DEBUG
    org.springframework.cloud.kubernetes.discovery: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

springdoc:
  swagger-ui:
    urls:
      - name: User
        url: /api/user/v3/api-docs

      - name: Payment
        url: /api/payment/v3/api-docs

      - name: Booking
        url: /api/booking/v3/api-docs

      - name: Festival
        url: /api/festival/v3/api-docs