server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    # Kubernetes 자동 Routing 설정 및 검색 범위 namespace 설정
    kubernetes:
      discovery:
        enabled: true
        namespaces:
          - booking
          - festival
          - payment
          - user
        # 검색 조건 : service 가 이 라벨을 포함할 경우
        service-labels:
          expose-via-spring-gateway: "true"
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: http://api-user-service.user.svc.cluster.local:8080
              predicates:
                - Path=/api/user/**,/api/addresses/**,/api/admin/**,/api/users/**,/api/mail/**,/api/auth/**,/api/myPage/**

            - id: user-swagger
              uri: http://api-user-service.user.svc.cluster.local:8080
              predicates:
                - Path=/api/user/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1


            - id: payment
              uri: http://api-payment-service.payment.svc.cluster.local:8080
              predicates:
                - Path=/api/payments/**,/api/tekcitpay/**

            - id: payment-swagger
              uri: http://api-payment-service.payment.svc.cluster.local:8080
              predicates:
                - Path=/api/payment/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1


            - id: booking
              uri: http://api-booking-service.booking.svc.cluster.local:8080
              predicates:
                - Path=/api/booking/**,/api/qr/**,/api/host/**,/api/capcha/**,/api/transfer/**,/api/ticket/**,/api/statistics/**,/ws/**

            - id: booking-swagger
              uri: http://api-booking-service.booking.svc.cluster.local:8080
              predicates:
                - Path=/api/booking/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1

            - id: festival
              uri: http://api-festival-service.festival.svc.cluster.local:8080
              predicates:
                - Path=/api/festival/**,/uploads/**

            - id: festival-swagger
              uri: http://api-festival-service.festival.svc.cluster.local:8080
              predicates:
                - Path=/api/festival/v3/api-docs
              filters:
                - StripPrefix=2
              order: -1


# JWT key 세팅
jwt:
  private-pem-path: classpath:keys/private.pem
  public-pem-path: classpath:keys/public.pem


# cors url 설정
cors:
  url:
    - http://localhost:5173
    - http://127.0.0.1:5173
    - http://localhost:5174
    - http://127.0.0.1:5174
    - https://www.rookies-tekcit.com
    - http://www.rookies-tekcit.com


# actuator 노출 범위, 조건
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.discovery: DEBUG
    org.springframework.cloud.kubernetes.discovery: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

springdoc:
  swagger-ui:
    urls:
      - name: User
        url: /api/user/v3/api-docs

      - name: Payment
        url: /api/payment/v3/api-docs

      - name: Booking
        url: /api/booking/v3/api-docs

      - name: Festival
        url: /api/festival/v3/api-docs