server:
  port: 10000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          # 각 MSA 서비스 라우팅을 위한 설정. uri 가 어떻게 이루어져있는지 파악되지 않아서 predicates ** 처리
          routes:
            - id: user
              uri: http://localhost:8080
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: payment
              uri: http://localhost:8081
              predicates:
                - Path=/payment
              filters:
                - StripPrefix=1
            - id: booking
              uri: http://localhost:8082
              predicates:
                - Path=/booking/**
              filters:
                - StripPrefix=1
            - id: festival
              uri: http://localhost:8083
              predicates:
                - Path=/festival/**
              filters:
                - StripPrefix=1
jwt:
  private-pem-path: classpath:keys/private.pem
  public-pem-path: classpath:keys/public.pem


# cors url 설정
cors:
  url: http://localhost:5173


management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.discovery: DEBUG
    org.springframework.cloud.kubernetes.discovery: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

springdoc:
  swagger-ui:
    urls:
      - name: User
        url: /user/v3/api-docs

      - name: Payment
        url: /payment/v3/api-docs

      - name: Booking
        url: /booking/v3/api-docs

      - name: Festival
        url: /festival/v3/api-docs